[start]
command:/usr/local/etc/rc.d/tcpgeo start
parameters:
type:script
message:Starting TCPGeo globe server
description:Start TCPGeo

[stop]
command:/usr/local/etc/rc.d/tcpgeo stop
parameters:
type:script
message:Stopping TCPGeo globe server
description:Stop TCPGeo

[restart]
command:/usr/local/etc/rc.d/tcpgeo restart
parameters:
type:script
message:Restarting TCPGeo globe server
description:Restart TCPGeo

[status]
command:/usr/local/opnsense/scripts/tcpgeo/status.sh
parameters:
type:script_output
message:Checking TCPGeo status
description:TCPGeo status

[reconfigure]
command:/usr/local/opnsense/scripts/tcpgeo/reconfigure.sh
parameters:
type:script
message:Reconfiguring TCPGeo
description:Reconfigure TCPGeo

[download-geoip]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/tcpgeo/download_geoip.py
parameters:
type:script_output
message:Downloading GeoIP database
description:Download GeoIP DB
