#!/usr/local/bin/python3
"""
TCPGeo OPNsense - Globe Server (Python/aiohttp)
Lightweight async web server for the 3D traffic globe.
Reads config from /usr/local/etc/tcpgeo/config.json (generated by OPNsense).
Captures traffic locally via tcpdump, resolves GeoIP, streams to globe via WebSocket.
"""

import asyncio
import json
import os
import signal
import ssl
import sys
import logging
from pathlib import Path
import base64
import hmac
import time
from collections import defaultdict

from aiohttp import web

from capture import ConnectionTracker
from geoip_resolver import GeoIPResolver
from mqtt_client import MQTTPublisher

# ---- Logging ----
logging.basicConfig(
    level=logging.INFO,
    format='[tcpgeo] %(asctime)s %(levelname)s %(message)s',
    datefmt='%H:%M:%S'
)
log = logging.getLogger('tcpgeo')

# ---- Config ----
CONFIG_PATH = os.environ.get('TCPGEO_CONFIG', '/usr/local/etc/tcpgeo/config.json')
SCRIPT_DIR = Path(__file__).parent
FRONTEND_DIR = SCRIPT_DIR / 'frontend'
FLUSH_INTERVAL = 1.0   # seconds between WebSocket flushes (was 0.5)
MAX_BUFFER = 500       # hard cap on in-memory buffer
MAX_PER_FLUSH = 60     # max packets sent per flush (rest is sampled/dropped)

# ---- Security: WebSocket Limits ----
MAX_WS_CLIENTS = 10         # max simultaneous WebSocket connections
WS_RATE_LIMIT = 5           # max new WS connects per IP per minute
WS_HEARTBEAT = 30.0         # ping interval in seconds


def load_config():
    """Load configuration from JSON file generated by OPNsense"""
    try:
        with open(CONFIG_PATH, 'r') as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError) as e:
        log.error('Config nicht gefunden oder fehlerhaft: %s (%s)', CONFIG_PATH, e)
        return {
            'enabled': False,
            'listenAddress': '127.0.0.1',
            'listenPort': 3333,
            'wanDevices': [],
            'wanIPs': [],
            'lanDevices': [],
            'lanIPs': [],
            'localLat': 50.0,
            'localLon': 10.0,
            'maxmindKey': '',
            'portColors': {},
            'globePassword': '',
            'maskIPs': True
        }


# ---- Global State ----
config = load_config()
geoip = GeoIPResolver(SCRIPT_DIR / 'geoip' / 'GeoLite2-City.mmdb')
capture = None
mqtt_pub = None
ws_clients = set()
packet_buffer = []
ws_rate_log = defaultdict(list)  # IP → [connect timestamps]


# ---- Security: Basic Auth Middleware ----
@web.middleware
async def auth_middleware(request, handler):
    """Require HTTP Basic Auth if a globe password is configured"""
    password = config.get('globePassword', '')
    if not password:
        return await handler(request)
    auth_header = request.headers.get('Authorization', '')
    if auth_header:
        try:
            scheme, data = auth_header.split(' ', 1)
            if scheme.lower() == 'basic':
                decoded = base64.b64decode(data).decode('utf-8')
                _, pwd = decoded.split(':', 1)
                if hmac.compare_digest(pwd, password):
                    return await handler(request)
        except Exception:
            pass
    return web.Response(
        status=401,
        headers={'WWW-Authenticate': 'Basic realm="TCPGeo Globe"'},
        text='Unauthorized'
    )


def mask_ip(ip):
    """Mask last octet of IPv4 address for privacy"""
    parts = ip.rsplit('.', 1)
    return parts[0] + '.xxx' if len(parts) == 2 else ip


# ---- WebSocket Handler ----
async def websocket_handler(request):
    """Handle WebSocket connections from the globe frontend"""
    # ---- Connection limit ----
    if len(ws_clients) >= MAX_WS_CLIENTS:
        return web.Response(status=503, text='Too many connections')

    # ---- Per-IP rate limit ----
    client_ip = request.remote or 'unknown'
    now = time.time()
    ws_rate_log[client_ip] = [t for t in ws_rate_log[client_ip] if now - t < 60]
    if len(ws_rate_log[client_ip]) >= WS_RATE_LIMIT:
        log.warning('Rate limit f\u00fcr %s erreicht', client_ip)
        return web.Response(status=429, text='Rate limit exceeded')
    ws_rate_log[client_ip].append(now)

    ws = web.WebSocketResponse(heartbeat=WS_HEARTBEAT)
    await ws.prepare(request)
    ws_clients.add(ws)
    log.info('Client verbunden (%d aktiv)', len(ws_clients))

    # Send config to client
    try:
        await ws.send_json({
            'type': 'config',
            'data': {
                'portColors': config.get('portColors', {}),
                'localLat': config.get('localLat', 50.0),
                'localLon': config.get('localLon', 10.0),
                'showClients': config.get('showClients', False)
            }
        })

        # Send current capture status
        if capture and capture.is_running():
            await ws.send_json({'type': 'status', 'data': 'capturing'})

    except Exception as e:
        log.warning('Fehler beim Senden der Config: %s', e)

    # Keep connection alive, handle incoming messages
    try:
        async for msg in ws:
            pass  # Globe frontend is read-only, no incoming messages expected
    except asyncio.CancelledError:
        pass
    except Exception:
        pass
    finally:
        ws_clients.discard(ws)
        log.info('Client getrennt (%d aktiv)', len(ws_clients))
        if not ws.closed:
            await ws.close()

    return ws


# ---- HTTP Handlers ----
async def api_config(request):
    """Return configuration for frontend"""
    return web.json_response({
        'portColors': config.get('portColors', {}),
        'localLat': config.get('localLat', 50.0),
        'localLon': config.get('localLon', 10.0),
        'showClients': config.get('showClients', False)
    })


async def api_geoip_status(request):
    """Return GeoIP database status"""
    return web.json_response({'ready': geoip.is_ready()})


async def index_handler(request):
    """Serve index.html for all non-API/non-ws routes"""
    return web.FileResponse(FRONTEND_DIR / 'index.html')


# ---- Packet Flushing ----
async def flush_packets():
    """Periodically send buffered packets to all connected WebSocket clients.
    SYN packets (new connections) are always sent; enrichment updates are
    sampled if the total batch exceeds MAX_PER_FLUSH."""
    global packet_buffer
    while True:
        await asyncio.sleep(FLUSH_INTERVAL)
        if not packet_buffer or not ws_clients:
            # Clear buffer even if no clients to prevent memory buildup
            if packet_buffer and not ws_clients:
                packet_buffer = []
            continue

        buf = packet_buffer
        packet_buffer = []

        # Separate new connections from enrichment updates so SYNs are never
        # dropped by sampling when an enrichment burst floods the buffer.
        new_pkts = []
        update_pkts = []
        for p in buf:
            if p.get('update'):
                update_pkts.append(p)
            else:
                new_pkts.append(p)

        # Always include all new connection packets (SYN-only → low volume)
        # Sample enrichment updates if over budget
        remaining = MAX_PER_FLUSH - len(new_pkts)
        if remaining <= 0:
            # Extremely unlikely: more SYNs than MAX_PER_FLUSH
            batch = new_pkts[:MAX_PER_FLUSH]
        elif len(update_pkts) <= remaining:
            batch = new_pkts + update_pkts
        else:
            # Sample enrichment updates evenly
            step = len(update_pkts) / remaining
            sampled = []
            idx = 0.0
            while len(sampled) < remaining and int(idx) < len(update_pkts):
                sampled.append(update_pkts[int(idx)])
                idx += step
            batch = new_pkts + sampled

        msg = json.dumps({'type': 'packets', 'data': batch})
        dead = set()
        for ws in ws_clients:
            try:
                await ws.send_str(msg)
            except Exception:
                dead.add(ws)
        ws_clients.difference_update(dead)


# ---- Capture Callback ----
def on_packet(pkt):
    """Called by ConnectionTracker for each captured connection"""
    global packet_buffer

    remote_ip = pkt['remoteIP']
    geo = geoip.resolve(remote_ip)
    if geo is None:
        return

    service_port = pkt['servicePort']
    port_key = str(service_port)
    port_conf = config.get('portColors', {}).get(port_key)
    color = port_conf['color'] if port_conf else None
    port_label = port_conf['label'] if port_conf else None

    # Include local client IP if showClients is enabled
    local_ip = pkt.get('localIP')
    entry = {
        'ip': mask_ip(remote_ip) if config.get('maskIPs', True) else remote_ip,
        'lat': geo['lat'],
        'lon': geo['lon'],
        'country': geo['country'],
        'city': geo['city'],
        'port': service_port,
        'direction': pkt['direction'],
        'color': color,
        'portLabel': port_label,
        'bytes': pkt.get('bytes', 0)
    }
    if pkt.get('update'):
        entry['update'] = True
    if config.get('showClients', False) and local_ip:
        entry['localIP'] = local_ip

    packet_buffer.append(entry)

    # Feed MQTT publisher (if active)
    if mqtt_pub:
        mqtt_pub.on_packet(entry)

    # Overflow protection
    if len(packet_buffer) > MAX_BUFFER:
        packet_buffer[:] = packet_buffer[-MAX_PER_FLUSH:]


def on_capture_status(status):
    """Called when capture status changes"""
    log.info('Capture Status: %s', status)
    # Broadcast to all clients
    msg = json.dumps({'type': 'status', 'data': status})
    for ws in list(ws_clients):
        try:
            asyncio.get_event_loop().create_task(ws.send_str(msg))
        except Exception:
            pass


def on_capture_error(err):
    """Called on capture error"""
    log.error('Capture Fehler: %s', err)


# ---- Resolve Local Position ----
def resolve_local_position():
    """Try to determine the firewall's geolocation from its public IP"""
    for ip in config.get('wanIPs', []):
        geo = geoip.resolve(ip)
        if geo and geo['lat'] and geo['lon']:
            config['localLat'] = geo['lat']
            config['localLon'] = geo['lon']
            log.info('Lokale Position: %.2f, %.2f (%s, %s)',
                     geo['lat'], geo['lon'], geo['city'], geo['country'])
            return
    log.info('Lokale Position nicht ermittelbar, verwende Default: %.2f, %.2f',
             config.get('localLat', 50.0), config.get('localLon', 10.0))


# ---- Capture Auto-Restart ----
async def capture_watchdog():
    """Restarts capture if it dies unexpectedly"""
    global capture
    while True:
        await asyncio.sleep(5)
        if capture and not capture.is_running():
            log.warning('Capture beendet, starte neu...')
            start_capture()


def start_capture():
    """Start the ConnectionTracker (SYN-only multi-interface capture)"""
    global capture
    wan_devices = config.get('wanDevices', [])
    lan_devices = config.get('lanDevices', [])
    wan_ips = config.get('wanIPs', [])
    lan_ips = config.get('lanIPs', [])
    log.info('Starte ConnectionTracker (WAN: %s, LAN: %s)',
             ', '.join(wan_devices) or '(keine)',
             ', '.join(lan_devices) or '(keine)')

    capture = ConnectionTracker(
        wan_devices=wan_devices,
        lan_devices=lan_devices,
        wan_ips=wan_ips,
        lan_ips=lan_ips,
        on_packet=on_packet,
        on_status=on_capture_status,
        on_error=on_capture_error
    )
    capture.start()


def start_mqtt():
    """Start MQTTPublisher if MQTT export is enabled in config."""
    global mqtt_pub
    if not config.get('mqttEnabled', False):
        log.info('MQTT Export deaktiviert')
        return
    server = config.get('mqttServer', '')
    if not server:
        log.warning('MQTT aktiviert aber kein Server konfiguriert')
        return
    mqtt_pub = MQTTPublisher(
        host=server,
        port=config.get('mqttPort', 1883),
        username=config.get('mqttUsername') or None,
        password=config.get('mqttPassword') or None,
        base_topic=config.get('mqttTopic', 'tcpgeo'),
        interval=config.get('mqttInterval', 60),
        mask_ips=config.get('maskIPs', True),
    )
    mqtt_pub.start()


# ---- Static file handler ----
async def static_file_handler(request):
    """Serve static files from the frontend directory, fallback to index.html"""
    fname = request.match_info.get('filename', '')

    if fname and '..' not in fname:
        fpath = (FRONTEND_DIR / fname).resolve()
        frontend_resolved = FRONTEND_DIR.resolve()
        # Check file exists and is inside (or equal to) the frontend dir
        if fpath.is_file() and fpath.is_relative_to(frontend_resolved):
            return web.FileResponse(fpath)

    # Fallback to index.html for any unknown path (SPA-style)
    return web.FileResponse(FRONTEND_DIR / 'index.html')


# ---- Main ----
async def on_startup(app):
    """Start background tasks when the app starts"""
    app['flush_task'] = asyncio.ensure_future(flush_packets())
    app['watchdog_task'] = asyncio.ensure_future(capture_watchdog())


async def init_app():
    """Initialize and return the aiohttp application"""
    app = web.Application(middlewares=[auth_middleware])

    # Lifecycle hooks
    app.on_startup.append(on_startup)

    # API and WebSocket routes FIRST (highest priority)
    app.router.add_get('/ws', websocket_handler)
    app.router.add_get('/api/config', api_config)
    app.router.add_get('/api/geoip/status', api_geoip_status)

    # Root serves index.html
    app.router.add_get('/', index_handler)

    # All other paths: try to serve as static file, fallback to index.html
    app.router.add_get('/{filename:.*}', static_file_handler)

    return app


async def on_shutdown(app):
    """Cleanup on server shutdown"""
    log.info('Fahre herunter... (PID %d)', os.getpid())
    # Cancel background tasks
    for task_name in ('flush_task', 'watchdog_task'):
        task = app.get(task_name)
        if task:
            task.cancel()
            try:
                await task
            except asyncio.CancelledError:
                pass
    # Close all WebSocket connections
    for ws in set(ws_clients):
        try:
            await ws.close()
        except Exception:
            pass
    ws_clients.clear()
    # Stop capture
    if capture:
        capture.stop()
    # Stop MQTT publisher
    if mqtt_pub:
        mqtt_pub.stop()
    # Close GeoIP
    geoip.close()


def main():
    if not config.get('enabled', False):
        log.info('Dienst ist deaktiviert. Beende.')
        sys.exit(0)

    host = config.get('listenAddress', '127.0.0.1')
    if host == '0.0.0.0':
        log.warning('Binding auf 0.0.0.0 nicht erlaubt, verwende 127.0.0.1')
        host = '127.0.0.1'
    port = config.get('listenPort', 3333)

    # ── Absorb premature SIGTERM/SIGINT during startup ──
    # On OPNsense, configd may send signals to the process group when the
    # rc.d start script exits.  We absorb them here so the server doesn't
    # die before aiohttp installs its own graceful-shutdown handlers.
    _startup_signals = []

    def _absorb_signal(signum, _frame):
        name = signal.Signals(signum).name
        _startup_signals.append(name)
        log.warning('Signal %s während Startup empfangen (absorbiert, PID %d)',
                     name, os.getpid())

    prev_term = signal.signal(signal.SIGTERM, _absorb_signal)
    prev_int  = signal.signal(signal.SIGINT,  _absorb_signal)

    log.info('==================================')
    log.info('TCPGeo OPNsense Globe Server  (PID %d)', os.getpid())
    log.info('==================================')

    # SSL/TLS setup
    ssl_context = None
    if config.get('enableSSL', False):
        cert_file = config.get('sslCertFile', '')
        key_file = config.get('sslKeyFile', '')
        if cert_file and key_file and os.path.exists(cert_file) and os.path.exists(key_file):
            try:
                ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
                ssl_context.minimum_version = ssl.TLSVersion.TLSv1_2
                ssl_context.load_cert_chain(cert_file, key_file)
                log.info('SSL/TLS aktiviert: %s', cert_file)
            except (ssl.SSLError, OSError) as e:
                log.error('SSL-Fehler: %s — starte ohne SSL', e)
                ssl_context = None
        else:
            log.warning('SSL aktiviert aber Zertifikat nicht gefunden — starte ohne SSL')

    protocol = 'https' if ssl_context else 'http'

    # Load GeoIP
    geoip.load()
    log.info('GeoIP bereit: %s', geoip.is_ready())

    # Resolve local position
    resolve_local_position()

    # Start MQTT publisher FIRST so it catches all packets from capture
    start_mqtt()

    # Start capture (may produce SYN burst immediately)
    start_capture()

    # Create app with shutdown hook
    app = asyncio.get_event_loop().run_until_complete(init_app())
    app.on_shutdown.append(on_shutdown)

    log.info('Globe erreichbar auf %s://%s:%d', protocol, host, port)

    if _startup_signals:
        log.warning('%d Signal(e) während Startup absorbiert: %s',
                     len(_startup_signals), ', '.join(_startup_signals))

    # Restore default handlers briefly so aiohttp can install its own.
    signal.signal(signal.SIGTERM, prev_term)
    signal.signal(signal.SIGINT,  prev_int)

    # run_app installs its own SIGTERM/SIGINT handlers for graceful shutdown
    try:
        web.run_app(
            app,
            host=host,
            port=port,
            ssl_context=ssl_context,
            print=None,
            handle_signals=True
        )
    except OSError as e:
        log.error('Server konnte Port %d nicht binden: %s', port, e)
        sys.exit(1)
    except Exception as e:
        log.error('Server-Fehler: %s', e, exc_info=True)
        sys.exit(1)
    finally:
        log.info('Server-Prozess beendet (PID %d)', os.getpid())


if __name__ == '__main__':
    main()
